---
engines:
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.go"
exclude_paths:
  - vendor/**/*
  - "**_test.go"
