package modules

import "github.com/bbuck/dragon-mud/scripting/lua"

// A type to map functions cleanly onto Lua meta tables (generated by Luar)
type luaMapper struct {
	pointerMethods map[string]interface{}
	methods        map[string]interface{}
}

// mapTo handles mapping the values set on to the meta table given.
func (lm *luaMapper) mapTo(mt *lua.Value) {
	if len(lm.pointerMethods) > 0 {
		ptrMethods := mt.RawGet("ptr_methods")
		for name, val := range lm.pointerMethods {
			ptrMethods.RawSet(name, val)
		}
	}

	for name, val := range lm.methods {
		mt.RawSet(name, val)
	}
}
